name: 🧪 e2e test

on: push

jobs:
  youki-build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [ "x86_64", "aarch64" ]
        libc: [ "gnu", "musl" ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1.3.7
        env:
          RUST_CACHE_KEY_OS: rust-cache-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install cross-rs
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Setup target
        run: |
          echo "CARGO=cross" >> ${GITHUB_ENV}
          echo "TARGET=${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}" >> ${GITHUB_ENV}
      - name: Build youki
        run: just youki-release
      - name: Upload youki binary
        if: ${{ matrix.arch == 'x86_64' }}
        uses: actions/upload-artifact@v4
        with:
          name: youki-${{ matrix.arch }}-${{ matrix.libc }}
          path: youki

  containerd-integration-tests:
    runs-on: ubuntu-22.04
    needs: [youki-build]
    timeout-minutes: 40
    strategy:
      matrix:
        arch: [ "x86_64" ]
        libc: [ "gnu", "musl" ]
    steps:
      - uses: actions/checkout@v4
        with:
          repository: containerd/containerd
          ref: v1.7.11
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20.12'
          cache: true
      - run: sudo apt-get -y update
      - run: sudo apt-get install -y pkg-config libsystemd-dev libelf-dev libseccomp-dev btrfs-progs libbtrfs-dev
      - name: Build containerd
        run: |
          make build
          make binaries
          sudo make install
          ./script/setup/install-cni
          ./script/setup/install-critools
      - name: Download youki binary
        uses: actions/download-artifact@v4
        with:
          name: youki-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Replace runc to youki
        run: |
          sudo rm -f /usr/bin/runc /usr/local/bin/runc /usr/sbin/runc
          sudo chmod 755 youki
          sudo cp youki /usr/bin/runc
          runc --version
      - name: Integration Test
        run: sudo make RUNC_FLAVOR=crun TEST_RUNTIME=io.containerd.runc.v2 TESTFLAGS="-timeout 40m" integration

  k8s-tests:
    runs-on: ubuntu-22.04
    needs: [youki-build]
    timeout-minutes: 40
    strategy:
      matrix:
        arch: [ "x86_64" ]
        libc: [ "gnu", "musl" ]
    steps:
      - uses: actions/checkout@v4
      - name: Download youki binary
        uses: actions/download-artifact@v4
        with:
          name: youki-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Add the permission to run
        run: chmod +x ./youki
      - name: Install just
        uses: taiki-e/install-action@just
      - name: test/k8s/deploy
        run: just test-kind

  oci-validation-go:
    runs-on: ubuntu-22.04
    needs: [youki-build]
    timeout-minutes: 15
    strategy:
      matrix:
        arch: [ "x86_64" ]
        libc: [ "gnu", "musl" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install just
        uses: taiki-e/install-action@just
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: true
          cache-dependency-path: tests/oci-runtime-tests/src/github.com/opencontainers/runtime-tools/go.sum
      - name: Download youki binary
        uses: actions/download-artifact@v4
        with:
          name: youki-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Add the permission to run
        run: chmod +x ./youki
      - name: Run integration tests
        run: just test-oci

  oci-validation-rust:
    runs-on: ubuntu-22.04
    needs: [youki-build]
    timeout-minutes: 20
    strategy:
      matrix:
        arch: [ "x86_64" ]
        libc: [ "gnu", "musl" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install requirements
        run: sudo env PATH=$PATH just ci-prepare
      - name: Download youki binary
        uses: actions/download-artifact@v4
        with:
          name: youki-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Add the permission to run
        run: chmod +x ./youki
      - name: Validate tests on youki
        run: just test-contest

  rootless-podman-test:
    runs-on: ubuntu-22.04
    needs: [youki-build]
    timeout-minutes: 20
    strategy:
      matrix:
        arch: [ "x86_64" ]
        libc: [ "gnu", "musl" ]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Rust toolchain and cache
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install requirements
        run: sudo env PATH=$PATH just ci-prepare
      - name: Download youki binary
        uses: actions/download-artifact@v4
        with:
          name: youki-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Add the permission to run
        run: chmod +x ./youki
      - name: Run tests
        run: just test-rootless-podman

  docker-in-docker-v1:
    runs-on: ubuntu-24.04
    needs: [youki-build]
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Install QEMU
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ovmf qemu-system-x86 qemu-utils
          sudo modprobe kvm
          # `sudo usermod -aG kvm $(whoami)` does not take an effect on GHA
          sudo chown $(whoami) /dev/kvm
      - name: Install Lima
        env:
          GITHUB_TOKEN: ${{ github.token }}  # required by `gh attestation verify`
        run: |
          set -eux
          LIMA_VERSION=$(curl -fsSL https://api.github.com/repos/lima-vm/lima/releases/latest | jq -r .tag_name)
          FILE="lima-${LIMA_VERSION:1}-Linux-x86_64.tar.gz"
          curl -fOSL https://github.com/lima-vm/lima/releases/download/${LIMA_VERSION}/${FILE}
          gh attestation verify --owner=lima-vm "${FILE}"
          sudo tar Cxzvf /usr/local "${FILE}"
          rm -f "${FILE}"
          # Export LIMA_VERSION For the GHA cache key
          echo "LIMA_VERSION=${LIMA_VERSION}" >>$GITHUB_ENV 
      - name: Cache ~/.cache/lima
        uses: actions/cache@v4
        with:
          path: ~/.cache/lima
          key: ${{ runner.os }}-lima-${{ env.LIMA_VERSION }}
      - name: Start an instance with Lima
        run: |
          # Add verbose logging
          limactl start --name=default --cpus=1 --memory=1 --network=lima:user-v2 .github/lima-templates/alma-v1.yaml
      - name: Download youki binary
        uses: actions/download-artifact@v4
        with:
          name: youki-x86_64-musl
      - name: Add the permission to run
        run: |
          # Ensure proper naming and permissions
          chmod +x ./youki
          ls -la ./youki
      - name: Run tests
        run: lima just test-dind-v1-lima

  docker-in-docker-v2:
    runs-on: ubuntu-22.04
    needs: [youki-build]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Download youki binary
        uses: actions/download-artifact@v4
        with:
          name: youki-x86_64-musl
      - name: Add the permission to run
        run: chmod +x ./youki
      - name: Run tests
        run: just test-dind
